export const TRANSACRION_DEPOSIT_REQUEST = 'TRANSACTION_DEPOSIT_REQUEST'
export const TRANSACRION_DEPOSIT_SUCCESS = 'TRANSACTION_DEPOSIT_SUCCESS'
export const TRANSACRION_DEPOSIT_FAIL = 'TRANSACTION_DEPOSIT_FAIL'
export const TRANSACRION_DEPOSIT_RESET = 'TRANSACTION_DEPOSIT_RESET'

export const TRANSACRION_WITHDRAW_REQUEST = 'TRANSACRION_WITHDRAW_REQUEST'
export const TRANSACRION_WITHDRAW_SUCCESS = 'TRANSACRION_WITHDRAW_SUCCESS'
export const TRANSACRION_WITHDRAW_FAIL = 'TRANSACRION_WITHDRAW_FAIL'
export const TRANSACRION_WITHDRAW_RESET = 'TRANSACRION_WITHDRAW_RESET'

export const TRANSACRION_TRANSFER_REQUEST = 'TRANSACRION_TRANSFER_REQUEST'
export const TRANSACRION_TRANSFER_SUCCESS = 'TRANSACRION_TRANSFER_SUCCESS'
export const TRANSACRION_TRANSFER_FAIL = 'TRANSACRION_TRANSFER_FAIL'
export const TRANSACRION_TRANSFER_RESET = 'TRANSACRION_TRANSFER_RESET'

export const TRANSACRION_SALDO_REQUEST = 'TRANSACRION_SALDO_REQUEST'
export const TRANSACRION_SALDO_SUCCESS = 'TRANSACRION_SALDO_SUCCESS'
export const TRANSACRION_SALDO_FAIL = 'TRANSACRION_SALDO_FAIL'
export const TRANSACRION_SALDO_RESET = 'TRANSACRION_SALDO_RESET'